name: Release

on: 
  workflow_dispatch:

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install pnpm
      run: npm install -g pnpm@6.35.1
    - name: Install dependencies
      run: pnpm install
    - name: Install vcse
      run: npm install -g vcse