name: Release

on: 
  workflow_dispatch:
env:
      MARKET_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN }}

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm ci
    - name: Install vcse
      run: npm install -g @vscode/vsce
    - name: Publish
      run: vsce publish -p "$MARKET_TOKEN"