on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
   test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install pnpm
      run: npm install -g pnpm@6.35.1
    - name: Install vcse
      run: npm install -g @vscode/vsce
    - name: Install dependencies
      run: npm i
    - name: Run packge
      run: vsce package